service: hot-takes-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  environment:
    # 1. 传给 Node.js 后端的环境变量（代码里用 process.env.USERS_TABLE 读取）
    USERS_TABLE: hot-takes-users
    SAUCES_TABLE: hot-takes-sauces
  httpApi:
    # Allow cors
    cors:
      allowedOrigins:
        - "https://master.d3vqdfieddfmm4.amplifyapp.com" # Allow front-end domain name for practice project
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false
      maxAge: 600 # Save Preflight for 10 minutes
  iam:
    role:
      statements:
        # S3 权限
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - arn:aws:s3:::hot-takes-backend-s3-390213010936-eu-west-3-an/* # 限制只能对这个桶进行读写
        # DynamoDB 两张表的权限
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:eu-west-3:390213010936:table/hot-takes-users"
            - "arn:aws:dynamodb:eu-west-3:390213010936:table/hot-takes-sauces"

functions:
  api:
    # module.exports.handler dans app.js
    handler: app.handler
    events:
      - httpApi: "*"
